### ISSUE TITLE
Why the site appears incorrectly

### ISSUE THREAD

**Issue by Oleg720** [minetest/minetest.github.io#102]
![screenshot_42](https://user-images.githubusercontent.com/29836552/28754872-cc088706-7567-11e7-9a54-3a8200aa7f53.png)

**Comment by SmallJoker** [comment]
Until a few moments the file `/assets/css/main.css` was missing, now everything looks right.

**Comment by Oleg720** [comment]
It's all worked, sorry

**Comment by rubenwardy** [comment]
The correct domain name is <minetest.net>, btw.
