### ISSUE TITLE
Terrible homepage description

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#108]
The homepage is really terrible:

> Meet Minetest.
> A free, open source voxel game engine and game. Fully extendable. You are in control.

Put yourselves in the shoes of a newbie. Do you really think a newbie would understand what Minetest is about? Probably not. This is a horrible way to present Minetest to first-time visitors.
Also, it's not even correct, “Minetest” is *only* the engine, not the game.

Let's brainstorm for text to put on the homepage. It should be succinct, to the point, explain Minetest's most important features reasonably complete. The goal is that a complete newbie might understand it and does not immediately close the browser tab.

My first suggestion:

> With **Minetest** you can play various games which are set in strange worlds made entirely out of blocks. You can build, dig, explore and do much more.
> Play alone or online with friends. Extend it with mods.

Feel free to suggest other summaries. :-)

PS: I'm not saying we should not mention that MT is FOSS, but it doesn't really belong in the very first sentence.

**Comment by rubenwardy** [comment]
That's way too verbose

**Comment by Wuzzy2** [comment]
> Feel free to suggest other summaries. :-)

**Comment by Wuzzy2** [comment]
> It also needs to focus on the variety of playing experiences

If fully agree, but this is hard to describe in words. There need to be a few selected high quality screenshots right on the landing page, which together give a decent impression of the *actual* gameplay. Current background looks incredibly boring (it even shows the old torch!!!).

You also need to keep in mind that the description need to be understood by newbies. Better a slightly longer description which everyone understands than a short description which nobody understands.

https://github.com/minetest/minetest.github.io/issues/78 already has tons of screenshots to choose from.

**Comment by dsohler** [comment]
> #78 already has tons of screenshots to choose from.

So has the forum, but instead of using bright, happy, awesome, and friendly screenshots for promotion all we have is a depressing dark background and a few dark, depressing, boring and outdated screenshots on the bottom of the page.

The summary is debatable but currently there is none and in the current form of the page there is no place for adding a proper description.

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest.github.io/commit/0f2c12a3ad96b1149084a3e611d0abbbcd07825b
