### ISSUE TITLE
Arrow bug with firefox

### ISSUE THREAD

**Issue by est31** [minetest/minetest.github.io#11]
See the (lovelessly cut :p) screenshot with firefox, the arrow has some "parts missing" on the right upper edge.
![arrow-bug](https://cloud.githubusercontent.com/assets/8872119/9570687/d55b8dd8-4f91-11e5-89c1-a186ed459572.png)
Chrome renders the arrow the right way:
![arrow-bug1](https://cloud.githubusercontent.com/assets/8872119/9570738/7bce6abe-4f92-11e5-995e-e9c33e2879cc.png)

**Comment by HybridDog** [comment]
The symbol of the forums also isn't scaled smoothly when l look at it at the bookmarks.
But the problem doesn't appear to the symbol of the main page.

**Comment by luk3yx** [comment]
Try changing the arrow to an image (full-size), and see how that works.
I get the same problem:
![screenshot](https://cloud.githubusercontent.com/assets/3182651/9647709/0b8e478e-5234-11e5-903a-d43e57b5b292.png)

**Comment by est31** [comment]
I wonder whether it is a gecko bug

**Comment by luk3yx** [comment]
It could be.

**Comment by est31** [comment]
Hrmm, from [playing around with the settings](fiddle.jshell.net/qktuh1Ly/3/) it seems to have problems with even numbers...

**Comment by est31** [comment]
Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=969763

**Comment by ShadowNinja** [comment]
@est31: I got the impression from that page that we could work around it by using an even size though...

**Comment by est31** [comment]
@ShadowNinja right now we have a size of 10, both 11 and 9 would work.

**Comment by ShadowNinja** [comment]
@est31:Choseone and apply it then.  I'd probably go for 11, but I'm fine with witchever.

**Comment by ShadowNinja** [comment]
b8e5a9a79f3783b6c8b6ad0f3edc1b0b8c7ee5e9

**Comment by est31** [comment]
cdd40f9aeced8719a9228aec53b3e0c79b33ea3b

**Comment by luk3yx** [comment]
Fixed! (I think)
It now renders correctly in Firefox:
![screenshot](https://cloud.githubusercontent.com/assets/3182651/9841895/7b478ada-5afa-11e5-9a0e-69908d3e95bd.png)
