### ISSUE TITLE
Does anyone care about this webpage at all?

### ISSUE THREAD

**Issue by Luraktinus** [minetest/minetest.github.io#110]

**Comment by rubenwardy** [comment]
Please be more specific about what you think is being neglected here. Also consider making a PR to fix any issues

**Comment by Luraktinus** [comment]
it seems outdated, the mods and the subgames

**Comment by rubenwardy** [comment]
#107

**Comment by Luraktinus** [comment]
other endusers pointed it out and indeed i have this feeling too...
