### ISSUE TITLE
Add a link to mods on ContentDB in the Mods section under Features

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest.github.io#127]
In [Features](https://www.minetest.net/#features) under `Large Collection of Existing Mods`, add a link to the mods sections of the forums like there is for games and texturepacks.

**Comment by rubenwardy** [comment]
Sounds good

**Comment by GreenXenith** [comment]
https://github.com/minetest/minetest.github.io/pull/128

**Comment by rubenwardy** [comment]
Should link to ContentDB instead
