### ISSUE TITLE
Certificate error accessing website

### ISSUE THREAD

**Issue by Dan291** [minetest/minetest.github.io#133]
![minetestwebsite](https://user-images.githubusercontent.com/38461073/41026390-59c56976-696c-11e8-895d-0c83e759ece2.png)

**Comment by sfan5** [comment]
@celeron55

**Comment by rubenwardy** [comment]
I recommend using a wildcard cert, less certs to manage and less to expire

And make a renew cronjob ofc

**Comment by rubenwardy** [comment]
Also, github supports HTTPS for custom domains now so you could point www.minetest.net directly at that
