### ISSUE TITLE
'Meet Minetest' is embarassing and tasteless as the primary text

### ISSUE THREAD

**Issue by paramat** [minetest/minetest.github.io#140]
'Meet ...' is a tasteless marketing phrase.
Makes me feel like 'Ewww' every time.
Just 'Minetest' is fine.

**Comment by benrob0329** [comment]
"What is Minetest" or "Minetest?" perhaps.

**Comment by SmallJoker** [comment]
`Play Minetest.` because why not?

**Comment by Ezhh** [comment]
Personally I would just remove the word "meet". It's an instant improvement with hardly any effort needed.

**Comment by paramat** [comment]
PR #141
