### ISSUE TITLE
Confusing information about webchat use on IRC -dev

### ISSUE THREAD

**Issue by paramat** [minetest/minetest.github.io#149]
From IRC http://irc.minetest.net/minetest/2018-11-17#i_5440860

23:25 Hawk777         On the IRC rules page: “Webchat cannot be used on #minetest-dev.” Also on the IRC rules page: a link to #minetest-dev in Webchat. Maybe someone should remove that?
23:27 Hawk777         Although, the wiki version of the IRC rules says Webchat users can actually join the channel, just not talk. So, perhaps the text just needs clarifying.

**Comment by rubenwardy** [comment]
They already made a PR
