### ISSUE TITLE
The downloads page is somehow get copyright claim and google censored them for it

### ISSUE THREAD

**Issue by tdzz** [minetest/minetest.github.io#151]
![img_20190106_001440](https://user-images.githubusercontent.com/45978566/50727406-52ef2a80-1112-11e9-9dd1-28f12ad28e35.jpg)
[Lumendatabese](https://www.lumendatabase.org/notices/17064869) link

**Comment by rubenwardy** [comment]
How do we contest this?

**Comment by celeron55** [comment]
This was the content of https://www.minetest.net/downloads/ on the reported date August 09, 2018: https://github.com/minetest/minetest.github.io/blob/6ac5b9450b14992d26af7978e064bdefd60a6d32/downloads.html

Anyone should be able to counter-notice this at https://support.google.com/legal/contact/lr_counternotice?product=websearch
