### ISSUE TITLE
pics jpg etc. - tell me to load it local if not wanted

### ISSUE THREAD

**Issue by ghost** [minetest/minetest.github.io#160]
Hello,
on the copy pages of www.minetest.one I only translate yet.
I don't change any code, so still loading pics, jpg etc. from original.

Please tell if I have to change to local storage at minetest.one, if load it so hard or not wished.

ready yet:
Thai th.minetest.one
German de.minetest.one

Greets
Thomas / Explorer / Festus1965

**Comment by rubenwardy** [comment]
Please don't make your site look like .net, as it will cause confusing

I don't see any problem with linking directly to the images from .net though, except that they may change without notice

**Comment by Minetest-One** [comment]
What kind of confusing is that, and what should be different ?
As I am NOT adverb for another thing than minetest itself ... and google users are also not confused when they get there own language shown on the same layout.

So I got that Idea as I found minetest.cn, the same but not from me. and I saw no complain !

So I stopped any further translation as I am no confused ...
