### ISSUE TITLE
Is Arch Linux unstable link still recommended?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#164]
I noticed on <https://www.minetest.net/downloads/> the link to Arch Linux unstable is this:

https://aur.archlinux.org/packages/minetest-git-leveldb/

But it points to something from 2016, apparently. o_O

Is this leveldb package thingie really still recommended?

I would guess the real package should be

https://aur.archlinux.org/packages/minetest-git

instead.

**Comment by rubenwardy** [comment]
That would be a better link

**Comment by sofar** [comment]
Agreed

**Comment by sfan5** [comment]
AUR provides source packages, just because the version says 2016 doesn't mean it's outdated
That said, `minetest-git` might still be the better choice to link to

**Comment by benrob0329** [comment]
We probably shouldn't link to a random community package script, Arch has fairly up to date versions already, and anyone looking at using the AUR should understand the risks going in.

**Comment by Linuxdirk** [comment]
> Arch has fairly up to date versions alread

Except for Minetest. Based on experience it takes up to 8 weeks for the maintainer to update the package after a new version.

**Comment by sfan5** [comment]
Links to different package since 36ca31c3355e7b8b0da5b4a504b8c41638eefdb8
