### ISSUE TITLE
Website is out?

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest.github.io#169]
Hello! Seems the domain of the site deosn't exist anymore, or isn't linked to anything! I cannot acess any part of the website nor link any image hosted on it! Is it just me?

**Comment by rubenwardy** [comment]
The VPS provider had a technical error which corrupted the hard drives (which were in RAID), the server is being rebuilt from backups. The wiki and forums will be back when this is complete.

**Comment by azekillDIABLO** [comment]
Thanks for answering :D
