### ISSUE TITLE
Assets don't load when at certain paths

### ISSUE THREAD

**Issue by CraigyDavi** [minetest/minetest.github.io#17]
For example, at the page http://www.minetest.net/assets/dont/load the assets for the 404 page don't load.

We should use `{{ site.baseurl }}` to include assets:
```
{{ site.baseurl }}/assets/css/main.min.css
```

**Comment by fabienwang** [comment]
I suggest you do that using the base html tag:
<base href="/">

/ should be okay as the website is hosted on a virtualhost and not in a subdir.
