### ISSUE TITLE
Link Lua API in Footer results in a 404

### ISSUE THREAD

**Issue by mmattes** [minetest/minetest.github.io#174]
Neither https://minetest.net/lua_api/ or https://www.minetest.net/lua_api/ are available. Probably it should link to https://github.com/minetest/minetest/blob/master/doc/lua_api.txt but i was not sure why i opened up an issue rather then a PR

**Comment by pauloue** [comment]
How about getting a subdomain for http://minetest.gitlab.io/minetest/ (api.minetest.net ?) and linking that instead?

**Comment by rubenwardy** [comment]
/lua_api used to redirect to that.
 
Maybe a page should be created with links to the raw text, the nice HTML version, and the wiki?

**Comment by Calinou** [comment]
I guess we could link to the nicely-formatted version directly, as it's far easier to read.

**Comment by rubenwardy** [comment]
> I guess we could link to the nicely-formatted version directly (from the Minetest Modding Book), as it's far easier to read.

http://minetest.gitlab.io/minetest is the official nice to read version
