### ISSUE TITLE
Old forum links don't work

### ISSUE THREAD

**Issue by mbartlett21** [minetest/minetest.github.io#187]
Old forum links like [this](https://www.minetest.net/forum/viewtopic.php?id=628) should get redirected to the proper location (https://forum.minetest.net/viewtopic.php?id=628)

**Comment by Calinou** [comment]
I'll try to fix it this week. It likely involves setting up a `forum.html` page (which will be generated as `/forum`), then redirecting the user based on GET parameters using JavaScript.
