### ISSUE TITLE
Gallery improvement

### ISSUE THREAD

**Issue by ObaniGemini** [minetest/minetest.github.io#19]
I think that website's gallery should be improved.
Actually, the main problem is that screenshots aren't varied enough.

What would be a nice thing to add :
- photos with mods
- photos with buildings
- photos with other players (and with varied armors/skins ?)

Also, I think there aren't enough display effects on screenshots (like mipmap, for example)

**Comment by Calinou** [comment]
Screenshots should use the maximum "default-looking" graphical options:

- Shaders enabled
- MSAA set to 4
- Bumpmapping disabled

**Comment by est31** [comment]
Hi, @ObaniGemini !

**Comment by rubenwardy** [comment]
duplicate of #78 (closing this one as it has less content, even if it's older)
