### ISSUE TITLE
Redirect to a "Thank you..." page after downloading MT

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest.github.io#193]
After downloading MT/MTG, it should redirect you to a `Thank you for downloading Minetest` page, with more information such as commonly used mods, games, texture packs, the Forums, the wiki, and more.

What do you think?

**Comment by SmallJoker** [comment]
Related: #129

**Comment by appgurueu** [comment]
I don't know, "Thank you for downloading <insert product name>" feels as if Minetest were commercial software.

**Comment by farooqkz** [comment]
> I don't know, "Thank you for downloading <insert product name>" feels as if Minetest were commercial software.

I have a similar thought. Why should Minetest Devs thank people for downloading their software? I believe the players must thank devs, both core devs and mod/subgame devs, for building and maintaining such a great thing.

**Comment by x2048** [comment]
The actual formulation may be different, for example here's Firefox 'thank you' page at `https://www.mozilla.org/en-US/firefox/download/thanks/`

![image](https://user-images.githubusercontent.com/4933697/212183698-1c9e76ee-e1f3-4775-9afd-15b360bdcb27.png)

**Comment by farooqkz** [comment]
> The actual formulation may be different, for example here's Firefox 'thank you' page at `https://www.mozilla.org/en-US/firefox/download/thanks/`
> 
> ![image](https://user-images.githubusercontent.com/4933697/212183698-1c9e76ee-e1f3-4775-9afd-15b360bdcb27.png)

I think Mozilla makes money using Firefox with default search engines.

**Comment by appgurueu** [comment]
~~I propose a "thank us" page instead.~~

**Comment by farooqkz** [comment]
@appgurueu I agree. A page to thank developers of Minetest of subgames with monthly donation with liberapay or something.

**Comment by appgurueu** [comment]
> @appgurueu I agree. A page to thank developers of Minetest of subgames with monthly donation with liberapay or something.

I think such a donation page should instead actually have donations go to the Minetest *core devs* - after all you're downloading the engine, not the (sub)games.

The correct place for a donation page for (sub)games would be ContentDB, which already has a "donate" button for each package. After downloading a (sub)game, the Minetest client could open a popup asking for a donation if this field is set. Same for the CDB website.

**Comment by farooqkz** [comment]
I agree the donations must go to core team. It must at least help with hosting costs if not the development. Regarding subgames, the current method is not good enough. But I think that's another discussion.

**Comment by Panquesito7** [comment]
A Liberapay team where all the developers get funded would be great. This would help Minetest a lot as well as encourage the devs to keep working.
But I think that's for another discussion, though
.

**Comment by farooqkz** [comment]
BTW, minetest has unclaimed donations at LP

**Comment by rubenwardy** [comment]
> BTW, minetest has unclaimed donations at LP

What does this mean?

**Comment by farooqkz** [comment]
> > BTW, minetest has unclaimed donations at LP
> 
> What does this mean?

This means some people are donating and you are not receiving. LP does not store anything

**Comment by rubenwardy** [comment]
There is no minetest organisation on liberapay though

**Comment by farooqkz** [comment]
https://liberapay.com/on/github/minetest
