### ISSUE TITLE
German Translations

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest.github.io#196]
Hi, i would like help translating the page to german. Is there a way to do it? I see no starts of translating

**Comment by Calinou** [comment]
Jekyll doesn't feature proper internationalization support yet, so I don't think this would be a good idea unless we migrated the site to use [Hugo](https://gohugo.io/).

**Comment by rubenwardy** [comment]
You don't necessarily need internationalization support. Minetest Modding Book is translated using folders, this makes sense as it's almost entirely text.

**Comment by rubenwardy** [comment]
duplicate of #26
