### ISSUE TITLE
Self-signed SSL certificate is used on minetest.net (but not www.minetest.net)

### ISSUE THREAD

**Issue by pi0neerpat** [minetest/minetest.github.io#200]
Just letting you all know!

**Comment by Calinou** [comment]
It seems `minetest.net` is a self-signed certificate whereas `www.minetest.net` is still a valid certificate signed by Let's Encrypt:

## minetest.net

![Certificate validity begin/end](https://user-images.githubusercontent.com/180032/77836171-39416500-7154-11ea-9253-603e72280144.png)

## www.minetest.net

![Certificate validity begin/end](https://user-images.githubusercontent.com/180032/77836181-41010980-7154-11ea-802d-692162fa668e.png)

**Comment by Calinou** [comment]
Bump :slightly_smiling_face:  The comment above is still relevant today (I just tried again).

**Comment by programmerjake** [comment]
minetest.net still uses the wrong cert.

**Comment by huantianad** [comment]
Bump since this issue still is a problem

**Comment by celeron55** [comment]
I tried to fix this and got rate limited by letsencrypt.org. Meanwhile minetest.net now has another self signed certificate.

Anyone know how long a ban I might have gotten?

**Comment by celeron55** [comment]
Rate limit cooldown looks to have passed and... knew it, this time it worked!

Please check if it looks fixed to you all.

**Comment by Calinou** [comment]
Working in Firefox 103:

![image](https://user-images.githubusercontent.com/180032/184370073-e83e079b-6604-467c-bfe3-9c8a862e8277.png)
