### ISSUE TITLE
Link to HTTPS version on README.md and description

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest.github.io#207]
Instead of linking to [`www.minetest.net`](http://www.minetest.net), please link to [`https://www.minetest.net`](https://www.minetest.net) for better security.

**Comment by Calinou** [comment]
See #183 which does this (except for the repository description, which I can't edit).

**Comment by Panquesito7** [comment]
> See #183

Is the PR going to be merged?

**Comment by Calinou** [comment]
@Panquesito7 I just merged it :slightly_smiling_face:
