### ISSUE TITLE
Wiki: Plaintext password emailed in confirmation

### ISSUE THREAD

**Issue by Jonta** [minetest/minetest.github.io#223]
Maybe it's a problem, maybe it's not. See https://security.stackexchange.com/questions/61215/the-registration-confirmation-email-contains-my-password-do-they-keep-it-in-pla

If passwords _are_ stored in plaintext: please fix, of course

And if they _aren't_: please alleviate our worries in that same email. :)

**Comment by Calinou** [comment]
This is done on the MediaWiki side. I don't think we can do much about it, since we'd rather not spend time doing customizations that would be lost when upgrading.

**Comment by rubenwardy** [comment]
Yeah, we didn't write the software used - it's the same software used on Wikipedia. Perhaps an update will fix this

**Comment by Jonta** [comment]
- Someone has access to the database to check, and if it's not: Hooray! Finding and then changing the email text sounds like not a lot of work
- Passwords aren't supplied by users, as creating an account is done by a mod, after a request in the forum thread
- Though some of us do use password managers, "everyone does" would be an unreasonable assumption

=)

**Comment by rubenwardy** [comment]
Sending the password by email when someone else creates the account is intentional and desirable. You can change your password afterwards
