### ISSUE TITLE
Superflous info in "Get involved" section

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest.github.io#226]
"How is Minetest developed" looks like something you expect to find either in the engine wiki or in a separate section in the site (and definitely not that long). Same for "Reporting issues", which is already mentioned in "Contribute -> Everyone". The donate section should have a separate page, but I guess it's not that important

**Comment by rubenwardy** [comment]
> How is Minetest developed" looks like something you expect to find either in the engine wiki or in a separate section in the site (and definitely not that long).

I disagree with this, it's important to have a summary with hooks to more content for transparency purposes. This is the proper place for it.

> Same for "Reporting issues", which is already mentioned in "Contribute -> Everyone".

The section in "Contribute > Everyone" links to "Reporting issues"
