### ISSUE TITLE
Promote F-Droid version on minetest.net/downloads/

### ISSUE THREAD

**Issue by r4dh4l** [minetest/minetest.github.io#227]
Hi,

related to https://github.com/minetest/minetest/issues/1786 it would be great to promote the [F-Droid version](https://f-droid.org/en/packages/net.minetest.minetest/) on https://www.minetest.net/downloads/ (at least as well). 

The note

> We advise not to use unofficial builds commonly found on the Play Store. They may contain excessive advertisements or spyware, or be distributed under proprietary terms. 

is great but offering just an APK download as alterantive and providing a logo for what you call "unofficial builds" is a little bit strange in this context.

It would be better if you would just promote the F-Droid version with a [logo](https://www.f-droid.org/en/2016/05/29/get-it-on-f-droid-badges.html) and just link the GooglePlay version in your nice warning, maybe like this:

***
***
***

[![Screenshot_2021-03-11_22-52-28](https://user-images.githubusercontent.com/44623983/110860027-8f9fa900-82bc-11eb-96b1-cb53bf0e8d24.png)](https://f-droid.org/en/packages/net.minetest.minetest/)

> Note: We advise not to use unofficial builds commonly found on the [Play Store](https://play.google.com/store/apps/details?id=net.minetest.minetest&utm_source=website&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1). They may contain excessive advertisements or spyware, or be distributed under proprietary terms. As much more secure and freedom respecting alternative you might want to use [f-droid](https://f-droid.org/en/) instead.

> Alternatively, [download the APK](https://github.com/minetest/minetest/releases/download/5.4.0/app-armeabi-v7a-release.apk). 

***
***
***

This would make the mintest downlaod section a great "best practice" reference for similar projects!

However: Thank you for mintest!

**Comment by rubenwardy** [comment]
The Play Store app linked is official. There are other apps that aren't official

F-Droid is currently outdated due to a build issue, so shouldn't be promoted

**Comment by r4dh4l** [comment]
> F-Droid is currently outdated due to a build issue, so shouldn't be promoted

I understand. What a pity.

> The Play Store app linked is official. There are other apps that aren't official

Ah, got it. My fault. For some reason I thought the warning is about the PlayStore in general. Sorry.

**Comment by Baerbeisser** [comment]
> F-Droid is currently outdated due to a build issue, so shouldn't be promoted

Anywhere to read up on this? I found nothing.
The F-Droid version still fails to launch on Android 10+ and the app downloaded manually doesn't update itself.

**Comment by Calinou** [comment]
F-Droid has strict requirements on the buildsystem – you can't bring your own binaries, everything must be built from source on their servers. Unfortunately, this makes building complex applications like Minetest difficult, so providing an APK is much easier.

Minetest doesn't get new releases that often and compatibility is rarely broken, so I think the APK is a fine way to play it if you don't want to use Google Play.

**Comment by rubenwardy** [comment]
The issue for this is https://gitlab.com/fdroid/fdroiddata/-/issues/2116

**Comment by Baerbeisser** [comment]
Thanks for the quick answers. Alright.

**Comment by rollerozxa** [comment]
F-Droid is up to date again now (and also contains 5.6 unlike Play), this should be added in addition to the current Google Play button and direct download link.
