### ISSUE TITLE
Please add Getting Started page for beginners

### ISSUE THREAD

**Issue by kenptr** [minetest/minetest.github.io#228]
Hi, I wanted to check out the project, downloaded it, but couldn't easily get started.

I didn't see any getting started page on minetest.net, if there is one, can you add link to the web site?

Thanks!

**Comment by rubenwardy** [comment]
Hi, the downloads page links here: https://wiki.minetest.net/Getting_started

Given you made this issue, this should probably be made more prominent

**Comment by kenptr** [comment]
you're right, I missed the "Getting Started" on https://www.minetest.net/downloads/ page :(

Thanks for pointing it out
