### ISSUE TITLE
Wording, and some minor issues

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest.github.io#23]
Main page:
  - [ ] `inspired by InfiniMiner, Minecraft and the like.` -- Comma after `Minecraft`.
  - [ ] `Minetest is available natively for Windows, OS X, GNU/Linux, Android, FreeBSD, and is Free/Libre and Open Source Software, released under the LGPL 2.1 or later.` -- There should be better separation between the list of O.S.es and the FOSS part. Perhaps split it into two sentences? (`...Android, and FreeBSD.  It is Free/Libre...`
  - [ ] `Play locally with your friends, or play online with dozens of players on a server.` -- I think this should mention single player as an option too. (`Play by yourself, locally with your friends, or online with dozens of players on a server.`)
  - [ ] Map generators section -- This should mention that you can also chose a mapgen from a mod.

Download(s):
  - [ ] The text about subgames seems to suggest that you should find one before trying Minetest.  Perhaps add `After you've tried Minetest you might want to try some mods or subgames`
  - [ ] The Arch Linux stable packages aren't listed: https://www.archlinux.org/packages/?q=minetest

Customize:
  - [ ] The `Texture packs` section should be expanded with a few examples (eg, HDX, BDCraft)

**Comment by est31** [comment]
Agree to all of the points, except the subgame one. For me the text seems fine.

**Comment by kilbith** [comment]
I personally find : `Minetest is a near-infinite-world block sandbox game and a game engine` a bit turgid and "heavy" on reading.

**Comment by rubenwardy** [comment]
> The text about subgames seems to suggest that you should find one before trying Minetest. Perhaps add After you've tried Minetest you might want to try some mods or subgames

I disagree with this, "Usually Minetest comes with Minetest Game" covers this. It could be made more clearer, however.
