### ISSUE TITLE
MineClone 2 screenshot image error

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#256]
The current MineClone 2 image is broken, it has a gray circle randomly added to it (somewhere top left). Did someone accidentally click the paintbrush in GIMP? :D

@zughy @rubenwardy

**Comment by sfan5** [comment]
Hopefully this well be a lesson not to rush in PRs.

**Comment by appgurueu** [comment]
> Original screenshot: https://satoshiupload.com/images/DWimu2CTrE.png

@rubenwardy already has the correct screenshot in his PR.
