### ISSUE TITLE
RAM and disk space requirements when unpacked and used though.

### ISSUE THREAD

**Issue by freesoftwarerocks** [minetest/minetest.github.io#264]
## Problem

A clear and concise description of what the problem is.
ie: Why is this needed?
Ex. I'm always frustrated when [...]

What is the RAM/Disk Space Requirements when unpacked and used?

**Comment by appgurueu** [comment]
Hard to tell; depends on platform and games/mods.

Disk: Less than 50 MB (often even much less) definitely suffice for Minetest. More should be recommended e.g. if you plan to get MCL, Dreambuilder or the like (which will probably be larger than MT).

RAM: I'd recommend at least 500 MB even for pretty "minimal" games to have some breathing room. For larger games like MCL I'd recommend at least 1 GB if not 2 GB.
