### ISSUE TITLE
Feature at least one screenshot with dynamic shadows in the homepage

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest.github.io#265]

**Comment by appgurueu** [comment]
(ideally dynamic shadows *and bloom* ;))

**Comment by rubenwardy** [comment]
Some of the screenshots from the 5.7.0 release post could be good candidates: https://blog.minetest.net/2023/04/08/5.7.0-released/#more-screenshots

**Comment by blkkatana** [comment]
I will do it.
