### ISSUE TITLE
error on building

### ISSUE THREAD

**Issue by testtest954** [minetest/minetest.github.io#277]
this error appears randomly here is everything
https://pastebin.com/HgTmBvyn

**Comment by x2048** [comment]
Might be fixed by removing nokogumbo as explicit dependency (see [here](https://github.com/rubys/nokogumbo)). I did not test it myself.

**Comment by testtest954** [comment]
remove nokogumbo

**Comment by rubenwardy** [comment]
Please try again, as I've updated the dependencies
