### ISSUE TITLE
Feature content creator's channels

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest.github.io#278]
There are many who create content. Maybe feature them in a page?

**Comment by rubenwardy** [comment]
This takes time to create and maintain, and anyone who isn't listed will feel left out. I think it's better and fairer for content creators just promote themselves, there's the "post your videos" forum topic, Mastodon, Reddit, and other platforms. Make good content and posts links to it from elsewhere

**Comment by celeron55** [comment]
It should probably be mentioned here also that if you publish something new, suggestions for the official blog are always open: https://github.com/minetest/blog/blob/master/.github/CONTRIBUTING.md
