### ISSUE TITLE
Verified Flathub package ?

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest.github.io#298]
The Flathub link is the recommended version of Minetest under Linux, so I would assume it's officially maintained? (at least as an end user)

![image](https://github.com/minetest/minetest.github.io/assets/61794590/9944ce74-d5ae-44b5-8116-e8f22f0633f7)

So I think it would make sense to make the Flathub app verified (which should be pretty easy, it's just a static file added to the website).

https://docs.flathub.org/docs/for-app-authors/verification

**Comment by rubenwardy** [comment]
Yes, the flatpak is official

Do you know if the verification method follows redirects? Our website is at www.minetest.net not minetest.net

**Comment by AFCMS** [comment]
Flathub has started giving unverified apps a big "unverified" label, which makes the situation worse IMO: they'll look completely unofficial. 

![image](https://github.com/minetest/minetest.github.io/assets/61794590/9395a0af-debb-4c01-b3d5-02ddd374f781)

**Comment by AFCMS** [comment]
Linux Mint software manager will now not only display unverified Flatpaks as insecure, but they will be hidden by default:

https://blog.linuxmint.com/?p=4719

**Comment by rubenwardy** [comment]
The main blocker for me here is that we do not have ownership or even write access to the flat hub Minetest repository. Are we supposed to?

**Comment by 1bcb** [comment]
You're supposed to.  Flathub has a policy that any upstream developer who wants access to the manifest repository can get it.  See [the documenation](https://docs.flathub.org/docs/for-app-authors/submission/#someone-else-has-put-my-app-on-flathubwhat-do-i-do).

> as part of setting up Flathub, some applications are being distributed on Flathub without the involvement of their developers. We would prefer that these applications are controlled by their authors.

> If an application that belongs to you is being distributed without your involvement, please get in touch with [the Flathub admins](mailto:admins@flathub.org), so that we can discuss transferring ownership.
