### ISSUE TITLE
Mention Lua Mapgens

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest.github.io#30]
Map generators section -- This should mention that you can also chose a mapgen from a mod. (from #23)

**Comment by rubenwardy** [comment]
From #23

**Comment by srifqi** [comment]
Agreed. Because there are plenty of mapgen mod in Minetest Forum. I wonder why until now this hasn't followed up.

**Comment by SmallJoker** [comment]
Why close?
I would like to see Lua mapgens (and carpathian) mentioned on the "Features" page.
