### ISSUE TITLE
The "About this website" text seems to be quite outdated by now

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest.github.io#31]
At the bottom of http://www.minetest.net/community/, we have the "About this website" text, copied word-to-word from the old website.

1) It should probably not list those names, because that list basically just contained whoever had access to edit the previous site.

2) It should probably link to this repository instead of saying "please contact us on IRC or forums."

Maybe the whole thing doesn't even have to exist anymore?

**Comment by Calinou** [comment]
> Maybe the whole thing doesn't even have to exist anymore?

I agree, it can be removed.

**Comment by naltamur** [comment]
Can we close?
