### ISSUE TITLE
Website is broken without JavaScript enabled

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#35]
The website does not work without JavaScript enabled.

Steps to reproduce:
- Be “paranoid” like me, and disable JavaScript
- Visit http://www.minetest.net/
- Click links in the top “bar” (?)

**Comment by est31** [comment]
IDK @ShadowNinja can we make piwik track the number of non-js requests? There are [some](http://stackoverflow.com/questions/9478737) numbers about it, but perhaps our visitors have a larger non-js percentage.

I personally have js enabled, because I never had any too negative experiences with it, unlike for flash.

If you know a way to solve the functionality we require without js, then I guess just make a PR.

**Comment by PilzAdam** [comment]
I don't enable JS, although minetest.net is whitelisted via noscript. I think websites as simple as this should work properly(!) without JS enabled.

**Comment by rubenwardy** [comment]
There was an IRC discussion about this, where I suggested a CSS navbar and Calinou was against it.

**Comment by ShadowNinja** [comment]
@est31: Didn't see it in the default views, although it could probably be added through the custom variables feature if it doesn't exist.
I definitely think that the site should be at least usable without JavaScript though.
@rubenwardy: Why?  Can you provide the logs?

**Comment by rubenwardy** [comment]
http://irc.minetest.ru/minetest-dev/2015-08-30#i_4381998

**Comment by ShadowNinja** [comment]
You can probably do click-only menus in css, but I think I'd prefer hover (or tap) menus since they're faster.
The issue of this being bootstrap's system is harder though.

**Comment by rubenwardy** [comment]
Still a problem

**Comment by luk3yx** [comment]
@ShadowNinja 
You could use the CSS :hover on a wrapper div.

**Comment by octacian** [comment]
I think the best solution to this would be to implement some sort of CSS navbar as originally suggested using CSS `:hover` which, if JavaScript were enabled, would be removed and current functionality would be kept.

**Comment by dsohler** [comment]
Actually this is quite simple.

https://codepen.io/anon/pen/LOOpvV

(No styling included just basic functionality.)

**Comment by Calinou** [comment]
@dsohler The goal is to reuse Bootstrap's styling (which provides a good-looking responsive navbar out of the box), not recreate our own.

I'm fairly sure Bootstrap can be tweaked to display dropdowns on hover rather than on click.

**Comment by dsohler** [comment]
As long as the site doesn’t need JS for core functionality like navigation it is all good.

**Comment by dsohler** [comment]
> I'm fairly sure Bootstrap can be tweaked to display dropdowns on hover rather than on click.

It is not about having hover or on-click for the navigation. It is about not needing to have Javascript enabled for such a basic core functionality like navigation.

**Comment by Calinou** [comment]
> It is not about having hover or on-click for the navigation. It is about not needing to have Javascript enabled for such a basic core functionality like navigation.

Yes, and using only CSS, you can only really have on-hover dropdowns. On-click dropdowns are possible with only CSS, but can get really hacky.
