### ISSUE TITLE
Broken appdata screenshot links

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#46]
The Minetest appdata file (`minetest.appdata.xml`) of Minetest 0.4.13 has two links for screenshots, namely:
- http://www.minetest.net/_media/screenshot_4032289578.png
- http://www.minetest.net/_media/screen2.png

Both links are broken. Since distributions are stuck with this appdata file for at least until the next Minetest release (Sometimes much longer for certain distributions. I am looking at you, Debian and Ubuntu!), I suggest you just upload some images at these exact paths.
According to the appdata file, the dimensions are 1440×851.

**Comment by est31** [comment]
The web archive has them archived, I am suprised:

* https://web.archive.org/web/20130606092126/http://minetest.net/_media/screen2.png?w=450
* https://web.archive.org/web/20130606102317/http://minetest.net/_media/screenshot_4032289578.png?w=450

**Comment by est31** [comment]
But I guess to load them back up one would need the full sized images. idk, perhaps sb has lying them around. If not, ppl could provide new screenshots. Any candidates?

**Comment by octacian** [comment]
Is this still an issue? There have been several releases since 0.4.16 so I would suppose that this could be closed.
