### ISSUE TITLE
Use HTTPS links instead of HTTP

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest.github.io#47]
Wherever possible, HTTPS should be used instead of HTTP. I found the following places where HTTP is explicitly set:
- `servers.html`
  - `servers.minetest.net` is linked with HTTP, but it supports HTTPS, so it should be changed.
- `irc.html`
  - `webchat.freenode.net` is linked with HTTP, but it supports HTTPS, so it should be changed.
- `README.md`
  - `jekyllrb.com` is linked with HTTP, but it supports HTTPS, so it should be changed.
  - `www.minetest.net` is linked with HTTP, but it supports HTTPS. The certificate is self-signed, though, so only change this when the certificate gets signed (AFAIK @celeron55 plans to use Let's Encrypt when it's available).
- `community.html`
  - `www.reddit.com` is linked with HTTP, but it supports HTTPS, so it should be changed.
- `development.html`
  - `forum.minetest.net` is linked with HTTP, but it supports HTTPS, so it should be changed.
  - `dev.minetest.net` (same as `www.minetest.net`)
- `downloads.html`
  - `minetest.net` (see above)
  - `dev.minetest.net` (see above)
- `customize.html`
  - `wiki.minetest.net` (same as `www.minetest.net`)
- `index.html`
  - `dev.minetest.net` (see above)

Where possible, these should be changed to explicitly use HTTPS, or leave the protocol out, so the currently chosen protocol of the user is used. I personally would say, that we link external sites explicitly with HTTPS, and internal links (e.g. the link to `minetest.net` in `downloads.html`) should have the front stripped.

(<b>Edited</b> by sfan5 2015-01-04: The serverlist now supports HTTPS)

**Comment by est31** [comment]
> I personally would say, that we link external sites explicitly with HTTPS, and internal links (e.g. the link to minetest.net in downloads.html) should have the front stripped.

:+1:

**Comment by est31** [comment]
`brew.sh` is missing from the list, but anyway, its github.io via a direct CNAME redirect, so https is broken for it.

**Comment by rugk** [comment]
Let's Encrypt is in public beta so you can now get certs for all your subdomains...

**Comment by rugk** [comment]
And BTW: You may improve your SSL/TLS config: https://www.ssllabs.com/ssltest/analyze.html?d=forum.minetest.net

**Comment by est31** [comment]
In fact, Let's encrypt is already in use: https://crt.sh/?CN=%25.minetest.net&iCAID=7395

**Comment by rugk** [comment]
Okay, but there are still domains without HTTPS.Most notably the main domain (minetest.net).
