### ISSUE TITLE
Use more usual cursor

### ISSUE THREAD

**Issue by eliemichel** [minetest/minetest.github.io#56]
Is it intended or the side effect of something else? Anyway, replacing `cursor: default` by `cursor: auto` in the `body` block of `main.css` fixes the weird behavior that the current cursor have (like, staying the basic arrow even when selecting some text).

**Comment by azekillDIABLO** [comment]
it doesn't cause any problem for me.

**Comment by eliemichel** [comment]
Do you have the text cursor when hovering text? Cause I don't! (neither using Chrome nor Firefox)

**Comment by Calinou** [comment]
> Do you have the text cursor when hovering text? Cause I don't! (neither using Chrome nor Firefox)

I don't either, but I intentionally added this. I've always found the default browser cursor effect to be strange (this is not a text-heavy site, or a site where you need to copy-paste things often), that said, if you really want me to revert it, I can.

**Comment by eliemichel** [comment]
All right, this answers the original "Is it intended" question then. :) I don't personnaly care, I was just wondering.
