### ISSUE TITLE
Steam Greenlight

### ISSUE THREAD

**Issue by scottviger** [minetest/minetest.github.io#57]
Hello developers,
I'm a fan and i was thinking of a way to help you.
i have a steam greenlight fee licenses and i want to help you get on steam.
i just want to be sure that your are ok with that (be on greelight).
i didn't knew where to put this message..
Please reply to my message at 301scottviger301@gmail.com
Thanks for your answer and don't forget to put all your questions in your reply!

**Comment by celeron55** [comment]
This is an utterly bad place to post that question. This is the github repository of the *website*. How did you even find your way into here?!

Putting Minetest on Steam isn't a matter of throwing it on greenlight; that's pointless. Someone has to maintain it there and adapt it to Steam's way of doing things. Based on what you just did, I don't believe you're someone that would properly adapt and maintain it for any length of time.

**Comment by scottviger** [comment]
well i tried to find your email... (;
