### ISSUE TITLE
New screenshots

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest.github.io#58]
I think the splash image is very boring (just a cave with torches).
I think something like this would look much better (by LazyJ):
![](https://dl.dropboxusercontent.com/u/30991334/mt_wikimedia/lazyjs_forge_afternoon_1920x1080.png)

**Comment by kilbith** [comment]
The current splash image (a cave) is regularly dark and uniform for a reason : the text color over there is white. So I think it offers a better contrast and readability.

**Comment by ShadowNinja** [comment]
Main site with LazyJ's image:
![screenshot_20160307_215951](https://cloud.githubusercontent.com/assets/3399154/13590679/efb87944-e4af-11e5-8741-7264a1030034.png)
Less readable perhaps, but not that bad -- and we can cut off the sky if readability's really an issue.

**Comment by rubenwardy** [comment]
What about at sunrise? You'd get a nice darker red glow with the sunset shaders

**Comment by celeron55** [comment]
Maybe that image could simply be darkened a bit? That's how I always edit my desktop wallpapers...

**Comment by srifqi** [comment]
> What about at sunrise? You'd get a nice darker red glow with the sunset shaders

> Maybe that image could simply be darkened a bit? That's how I always edit my desktop wallpapers...

We already have [this picture at sunset](https://commons.wikimedia.org/wiki/File:Minetest_LazyJ%27s_Forge_at_dusk.png).

![Minetest LazyJ's Forge at dusk](https://upload.wikimedia.org/wikipedia/commons/b/b7/Minetest_LazyJ%27s_Forge_at_dusk.png)

**Comment by Eater4** [comment]
It would be nice if you could get more of the flag at the top in the on the sample website

**Comment by Calinou** [comment]
Please take the screenshot with `fsaa = 4` (4× anti-aliasing).

**Comment by Eater4** [comment]
We need do do something like this if we have a more detailed picture for the homepage. (Currently working on getting the bar to reappear after scrolling past the picture.
![capture](https://cloud.githubusercontent.com/assets/7614846/13762204/4d4132da-ea0b-11e5-8474-e36405b6bdb6.PNG)

**Comment by srifqi** [comment]
That's nice, @Eater4!

The bar will be transparent and get solid with smooth animation based on the page's scroll.

**Comment by rubenwardy** [comment]
It doesn't look right with the logo or the photo's watermark

**Comment by rubenwardy** [comment]
even though this one was opened first, #78 has more content. So closing as duplicate
