### ISSUE TITLE
License compliance checklist

### ISSUE THREAD

**Issue by est31** [minetest/minetest.github.io#59]
Minetest has a copyleft license, and the question is how we should treat people developing apps that base on minetest, for places like the google play store.

The ffmpeg project has its own checklist for applications that want to use their code: https://www.ffmpeg.org/legal.html

Should we get such a similar checklist? Often we get support requests for how to build minetest for android from different people, those requests would be a good place to point them to such a checklist.

What would be the requirements the main copyright holders from @minetest/team-minetest would see?

An attempt from me:
- disclose use of minetest in the app desctiption on google play "This [app/game/...] uses the Minetest engine [and game], Copyright 2010-2016 Perttu Ahola celeron55@gmail.com
  and contributors, Licensed under the LGPL version 2.1 or later"
- If you don't modify engine source code:
  - Add a link to the minetest github page
- If you modify engine source code: 
  - Add a link to the place where the modified code can be downloaded
- disclose use of minetest in the app's main menu -- we don't have such a page currently ourselves in fact, the credits tab would be a good place for it, no?

**Comment by rubenwardy** [comment]
It would be good to have this somewhere. If not the website then the wiki.

**Comment by est31** [comment]
I guess this is implemented now http://wiki.minetest.net/Licensing#Complying_with_the_License
