### ISSUE TITLE
Android downloads page is still showing Minetest 0.4.13

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest.github.io#64]
Hello,
The Android downloads page is still showing Minetest 0.4.13.
Minetest 0.4.14 is available on Android, but this has not been updated.

**Comment by luk3yx** [comment]
I have created pull request #65. If that gets accepted, please close this issue.

**Comment by est31** [comment]
b71de1cc3c9f4ede2968e53131b7508625205d37
