### ISSUE TITLE
Add automated test for correct HTML

### ISSUE THREAD

**Issue by ExcaliburZero** [minetest/minetest.github.io#69]
Currently when pull requests are made for the project it is possible that they may have unintentional incorrect HTML. Such issues can be time consuming to check for, thus an automated test should be employed to check for such issues.

The test could be run using a service such as Travis CI.

Such a test could be made by using a program such as [html-proofer](https://github.com/gjtorikian/html-proofer).

**Comment by est31** [comment]
Seems there is a guide for this: https://jekyllrb.com/docs/continuous-integration/

@ExcaliburZero do you want to give it a try? You can try it on your local fork, then if it works there, you can open a PR.

**Comment by ExcaliburZero** [comment]
I have gotten the tests working through Travis CI using html-proofer, and opened a pull request (#70) with the changes.

**Comment by est31** [comment]
Awesome! Can you push a commit somewhere that shows a failure of the unit test?

**Comment by est31** [comment]
Err sorry, haven't read the PR description. NVM
