### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by est31** [minetest/minetest.github.io#74]
out of some reason, the CI builds are failing right now in master.

**Comment by rubenwardy** [comment]
```
Installing rb-fsevent 0.9.7
Installing kramdown 1.12.0
Installing liquid 3.0.6
Installing rouge 1.11.1
Installing safe_yaml 1.0.4
Using bundler 1.7.9
Installing tzinfo 1.2.2
Installing pathutil 0.14.0
Installing ffi 1.9.14
Installing jekyll-sass-converter 1.4.0
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
Installing nokogiri 1.6.8.1
An error occurred while installing activesupport (5.0.0.1), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.0.0.1'` succeeds before bundling.
```

**Comment by ExcaliburZero** [comment]
It looks like Bundler is having issues installing activesupport. According to the error message, it requires Ruby 2.2.2.

This can probably be fixed by changing the ruby version in the `.travis.yml` file to 2.2.2.

**Comment by ExcaliburZero** [comment]
This issue could be fixed by either changing Travis CI to use Ruby 2.2.2, or changing the `Gemfile` to use version 3.0.6 of html-proofer.

**Comment by est31** [comment]
Can you make a PR? It will then use the changed travis yml file.

**Comment by ExcaliburZero** [comment]
I have made a pull request with the change at #75.

**Comment by est31** [comment]
Thanks for the fix!
