### ISSUE TITLE
Add More content to the customize page

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest.github.io#76]
I think there should be more mods, subgames, and texture packs added To The customize page
Like The summerfields Texture Pack It is constantly updated
https://forum.minetest.net/viewtopic.php?f=4&t=9314

**Comment by tobyplowy** [comment]
@paramat ping

**Comment by paramat** [comment]
Not my department.

**Comment by rubenwardy** [comment]
Make a full list of what you'd like the page to say, and I'll look over it

FYI: c55, @Calinou and I are the main website maintainers (although core devs may edit)

**Comment by tobyplowy** [comment]
@paramat oh sorry you do so much work around here i diddent know :/ who do i speak with them

**Comment by tobyplowy** [comment]
@rubenwardy Will do 

I just Have To make a list of all the Community content that I think should be on the website am I right?

**Comment by tobyplowy** [comment]
texturepacks
Vanilla 32x32 https://forum.minetest.net/viewtopic.php?f=4&t=15758 (made by me)
Summerfields https://forum.minetest.net/viewtopic.php?f=4&t=9314 (i help with updates)
PixelPerfection https://forum.minetest.net/viewtopic.php?f=4&t=14289
mini8x https://forum.minetest.net/viewtopic.php?f=4&t=14633
PixelBOX Reloaded https://forum.minetest.net/viewtopic.php?f=4&t=14132

mods
X-Decor https://forum.minetest.net/viewtopic.php?t=12534
Not so simple mobs v2.4 [nssm] https://forum.minetest.net/viewtopic.php?f=11&t=11813
Advanced Trains https://forum.minetest.net/viewtopic.php?f=11&t=14726
Mars Survive 6 https://forum.minetest.net/viewtopic.php?f=11&t=13913
Hoppers https://forum.minetest.net/viewtopic.php?f=11&t=12379
bows https://forum.minetest.net/viewtopic.php?f=11&t=14384
pedology https://forum.minetest.net/viewtopic.php?f=11&t=9429
gravitygun https://forum.minetest.net/viewtopic.php?f=11&t=14056
nukes https://forum.minetest.net/viewtopic.php?f=11&t=638
colored_clay https://forum.minetest.net/viewtopic.php?f=11&t=15651
pie https://forum.minetest.net/viewtopic.php?f=11&t=13285
darkage https://forum.minetest.net/viewtopic.php?f=11&t=3213

wip mods 
zombies https://forum.minetest.net/viewtopic.php?f=9&t=14934
hell https://forum.minetest.net/viewtopic.php?f=9&t=15893
Chat Bubbles https://forum.minetest.net/viewtopic.php?f=9&t=15880
vehicles https://forum.minetest.net/viewtopic.php?f=9&t=15610
d00med mobs https://forum.minetest.net/viewtopic.php?f=9&t=14382

**Comment by tobyplowy** [comment]
@rubenwardy here you go :D

**Comment by tobyplowy** [comment]
@rubenwardy is this good?

**Comment by sfan5** [comment]
>Vanilla 32x32 https://forum.minetest.net/viewtopic.php?f=4&t=15758
PixelPerfection https://forum.minetest.net/viewtopic.php?f=4&t=14289
mini8x https://forum.minetest.net/viewtopic.php?f=4&t=14633
PixelBOX Reloaded https://forum.minetest.net/viewtopic.php?f=4&t=14132

seems fine

>Summerfields https://forum.minetest.net/viewtopic.php?f=4&t=9314

absolutely



> X-Decor https://forum.minetest.net/viewtopic.php?t=12534
Advanced Trains https://forum.minetest.net/viewtopic.php?f=11&t=14726
colored_clay https://forum.minetest.net/viewtopic.php?f=11&t=15651

seems fine

>Not so simple mobs v2.4 [nssm] https://forum.minetest.net/viewtopic.php?f=11&t=11813
Mars Survive 6 https://forum.minetest.net/viewtopic.php?f=11&t=13913
pedology https://forum.minetest.net/viewtopic.php?f=11&t=9429

not sure about these

>Hoppers https://forum.minetest.net/viewtopic.php?f=11&t=12379
nuke https://forum.minetest.net/viewtopic.php?f=11&t=638
darkage https://forum.minetest.net/viewtopic.php?f=11&t=3213

not updated for a year/longer?

>bows https://forum.minetest.net/viewtopic.php?f=11&t=14384
gravitygun https://forum.minetest.net/viewtopic.php?f=11&t=14056

cc0 license can't apply to code as far as i'm aware

> pie https://forum.minetest.net/viewtopic.php?f=11&t=13285

texture looks like copied from minecraft

> wip mods 

don't belong there IMO

**Comment by rubenwardy** [comment]
I agree with sfan5

**Comment by Calinou** [comment]
> cc0 license can't apply to code as far as i'm aware

While it is not OSI-approved, code can be put under a CC0 license, [like the FSF says](https://www.gnu.org/licenses/license-list.html#CC0).

**Comment by tobyplowy** [comment]
@sfan5 wow you really seem to love summerfields Not that thers a Reason not to Love It :D 

also in case you want to know we're already working on the new update for minetest :)

**Comment by tobyplowy** [comment]
@sfan5 would it be possible to have a mod browser On The minetest website Something similar to Planet Minecraft http://www.planetminecraft.com

**Comment by est31** [comment]
@tobyplowy see https://github.com/minetest/minetest/issues/3289

**Comment by tobyplowy** [comment]
@est31 @rubenwardy when will this be added to the website?

**Comment by tobyplowy** [comment]
@est31 @rubenwardy @sfan5 when will this be added to the website?
