### ISSUE TITLE
add a bitcoin, litecoin, or other bitcoin-like address

### ISSUE THREAD

**Issue by emuNAND** [minetest/minetest.github.io#81]
it would be nice to have a way to donate with bitcoin so we can have some "anonymous heroes"

**Comment by rubenwardy** [comment]
It's up to @celeron55 whether he'd like to get a bitcoin wallet

**Comment by neoascetic** [comment]
Bountysource page? There are few bucks on it...

**Comment by rubenwardy** [comment]
I doubt @celeron55 is going to do this, I'll close in a week if no response

**Comment by CasimirKaPazi** [comment]
What about @paramat ?
