### ISSUE TITLE
Blog url?

### ISSUE THREAD

**Issue by est31** [minetest/minetest.github.io#9]
In the `development` menu, there is a "blog" link pointing to @celeron55 's blog. Should we still have it? Should we have a blog on minetest.net instead? Does the news section in the forum already fulfil this purpose?

At least the blog url should be updated to something like: http://c55.me/blog/?cat=9

**Comment by celeron55** [comment]
I'm fine with replacing it with a link to the forum's news section or something.

**Comment by rubenwardy** [comment]
4b4d700f5e0e55ae03766bb60ca5780e3046d34e
