### ISSUE TITLE
Minetest Arch Unstable Build has Gone Unmaintained

### ISSUE THREAD

**Issue by kalebsanders007** [minetest/minetest.github.io#97]
Not sure what can be done about it, but it has gone stale.

**Comment by sofar** [comment]
#define stale

**Comment by sofar** [comment]
```
community/minetest 0.4.15-1
    Multiplayer infinite-world block sandbox game
community/minetest-common 0.4.15-1
    Common data files for minetest and minetest-server
community/minetest-server 0.4.15-1
    Server of infinite-world block sandbox game
```

looks up to date to me?

**Comment by sfan5** [comment]
He meant this one: https://aur.archlinux.org/packages/minetest-git-leveldb/

however i don't see how that is out of date

**Comment by nerzhul** [comment]
Also it's an AUR, i don't think we should care about this as AUR is not archlinux official
